import { QuestionType } from '@prisma/client';

export interface LabQuestionSeed {
  questionText: string;
  questionType?: QuestionType;
  options?: string[];
  correctAnswer?: string;
  points?: number;
  order?: number;
}

export interface LabSeed {
  key: string;
  title: string;
  subject: string;
  grade: string;
  topicArea?: string;
  pathway?: string;
  competency?: string;
  description?: string;
  durationMinutes?: number;
  resourceUrl?: string;
  guidanceSteps?: string[];
  questions?: LabQuestionSeed[];
}

// Full STEM Labs catalog, Junior School (Grades 7-9) and Senior School
// (Grades 10-12), as specified for Assignments Hub. Every lab gets a real
// catalog entry (grade/subject/topic/competency/duration/description) so
// the "STEM Labs" page has real content to browse and filter by grade.
//
// Only the pilot lab (DEMO-VOLCANO-1, appended at the end) has a real video
// (resourceUrl), narration script (guidanceSteps), and quiz questions — see
// the "1 full pilot lab" scoping decision. The other 57 are ready for a
// Platform Admin to attach a YouTube video + quiz to via PATCH /labs/:id
// (or re-running this seed after editing the entries below).
//
// SS-* (Senior School) lab IDs from the source curriculum table don't
// distinguish which of Grades 10/11/12 each lab belongs to — they're all
// numbered "-10-" as part of the ID, not a grade marker. Seeded here as
// "Grade 10"; adjust individual labs' `grade` via PATCH /labs/:id if a
// specific lab is actually meant for Grade 11 or 12.
export const LAB_CATALOG: LabSeed[] = [
  // ===================== JUNIOR SCHOOL — GRADE 7 =====================
  // (Integrated Science, per the rationalized CBC curriculum)
  {
    key: 'js7-lab1',
    title: 'Plant Growth Investigation',
    subject: 'Integrated Science',
    grade: 'Grade 7',
    topicArea: 'Scientific Investigation',
    competency: 'Scientific Inquiry',
    durationMinutes: 40,
    description: 'Simulate plant growth under different light, water, and soil conditions',
  },
  {
    key: 'js7-lab2',
    title: 'Water Purification Challenge',
    subject: 'Integrated Science',
    grade: 'Grade 7',
    topicArea: 'Environment & Conservation',
    competency: 'Problem Solving',
    durationMinutes: 45,
    description: 'Virtual water filtration system with different materials',
  },
  {
    key: 'js7-lab3',
    title: 'Simple Circuit Builder',
    subject: 'Integrated Science',
    grade: 'Grade 7',
    topicArea: 'Energy & Electricity',
    competency: 'Critical Thinking',
    durationMinutes: 40,
    description: 'Build series and parallel circuits with interactive components',
  },
  {
    key: 'js7-lab4',
    title: 'Heat Transfer Explorations',
    subject: 'Integrated Science',
    grade: 'Grade 7',
    topicArea: 'Energy',
    competency: 'Observation',
    durationMinutes: 35,
    description: 'Simulate conduction, convection, and radiation experiments',
  },
  {
    key: 'js7-lab5',
    title: 'First Aid Simulation',
    subject: 'Integrated Science',
    grade: 'Grade 7',
    topicArea: 'Health Education',
    competency: 'Health Literacy',
    durationMinutes: 45,
    description: 'Virtual first aid scenarios with step-by-step guidance',
  },
  {
    key: 'js7-lab6',
    title: 'Nutrition Tracker',
    subject: 'Integrated Science',
    grade: 'Grade 7',
    topicArea: 'Health Education',
    competency: 'Health Literacy',
    durationMinutes: 40,
    description: 'Interactive meal planning and nutrient analysis',
  },
  {
    key: 'js7-lab7',
    title: 'Water Testing Lab',
    subject: 'Integrated Science',
    grade: 'Grade 7',
    topicArea: 'Environment',
    competency: 'Scientific Inquiry',
    durationMinutes: 45,
    description: 'Virtual water quality testing with pH, turbidity, and contamination',
  },

  // ===================== JUNIOR SCHOOL — GRADE 8 =====================
  {
    key: 'js8-lab1',
    title: 'Acid-Base Chemistry Lab',
    subject: 'Integrated Science',
    grade: 'Grade 8',
    topicArea: 'Chemical Reactions',
    competency: 'Experimentation',
    durationMinutes: 45,
    description: 'Virtual mixing of acids and bases with pH indicators',
  },
  {
    key: 'js8-lab2',
    title: 'Human Body Explorer',
    subject: 'Integrated Science',
    grade: 'Grade 8',
    topicArea: 'Human Body Systems',
    competency: 'Systems Thinking',
    durationMinutes: 50,
    description: '3D interactive exploration of human body systems',
  },
  {
    key: 'js8-lab3',
    title: 'Simple Machines Workshop',
    subject: 'Integrated Science',
    grade: 'Grade 8',
    topicArea: 'Force & Motion',
    competency: 'Design Thinking',
    durationMinutes: 45,
    description: 'Build and test levers, pulleys, and inclined planes',
  },
  {
    key: 'js8-lab4',
    title: 'Electromagnet Construction',
    subject: 'Integrated Science',
    grade: 'Grade 8',
    topicArea: 'Electricity & Magnetism',
    competency: 'Problem Solving',
    durationMinutes: 45,
    description: 'Virtual electromagnet with adjustable coils and current',
  },
  {
    key: 'js8-lab5',
    title: 'Microscope Virtual Lab',
    subject: 'Integrated Science',
    grade: 'Grade 8',
    topicArea: 'Cell Biology',
    competency: 'Observation',
    durationMinutes: 40,
    description: 'Virtual microscope with plant and animal cells',
  },
  {
    key: 'js8-lab6',
    title: 'Digestive System Simulation',
    subject: 'Integrated Science',
    grade: 'Grade 8',
    topicArea: 'Human Body Systems',
    competency: 'Scientific Inquiry',
    durationMinutes: 45,
    description: 'Interactive journey through the digestive system',
  },
  {
    key: 'js8-lab7',
    title: 'Weather Station Simulation',
    subject: 'Integrated Science',
    grade: 'Grade 8',
    topicArea: 'Environment',
    competency: 'Data Analysis',
    durationMinutes: 45,
    description: 'Virtual weather station with temperature, pressure, and rainfall',
  },

  // ===================== JUNIOR SCHOOL — GRADE 9 =====================
  {
    key: 'js9-lab1',
    title: 'Genetics & Heredity Lab',
    subject: 'Integrated Science',
    grade: 'Grade 9',
    topicArea: 'Genetics',
    competency: 'Critical Thinking',
    durationMinutes: 50,
    description: 'Punnett square simulator with trait inheritance',
  },
  {
    key: 'js9-lab2',
    title: 'DNA Structure Explorer',
    subject: 'Integrated Science',
    grade: 'Grade 9',
    topicArea: 'Genetics',
    competency: 'Scientific Inquiry',
    durationMinutes: 45,
    description: '3D DNA model building and replication simulation',
  },
  {
    key: 'js9-lab3',
    title: 'Chemical Bonding Simulator',
    subject: 'Integrated Science',
    grade: 'Grade 9',
    topicArea: 'Chemical Bonding',
    competency: 'Spatial Reasoning',
    durationMinutes: 45,
    description: 'Interactive molecular model builder',
  },
  {
    key: 'js9-lab4',
    title: 'Wave Interference Lab',
    subject: 'Integrated Science',
    grade: 'Grade 9',
    topicArea: 'Waves & Sound',
    competency: 'Observation',
    durationMinutes: 45,
    description: 'Sound wave and interference pattern simulator',
  },
  {
    key: 'js9-lab5',
    title: 'Ecosystem Balance Simulator',
    subject: 'Integrated Science',
    grade: 'Grade 9',
    topicArea: 'Ecological Balance',
    competency: 'Systems Thinking',
    durationMinutes: 50,
    description: 'Predator-prey dynamics with population tracking',
  },
  {
    key: 'js9-lab6',
    title: 'Electrolysis Lab',
    subject: 'Integrated Science',
    grade: 'Grade 9',
    topicArea: 'Chemical Reactions',
    competency: 'Experimentation',
    durationMinutes: 45,
    description: 'Virtual electrolysis with different solutions',
  },
  {
    key: 'js9-lab7',
    title: 'Climate Change Simulator',
    subject: 'Integrated Science',
    grade: 'Grade 9',
    topicArea: 'Environment',
    competency: 'Systems Thinking',
    durationMinutes: 50,
    description: 'Simulate greenhouse gas effects on global temperatures',
  },

  // ===================== SENIOR SCHOOL — BIOLOGY =====================
  {
    key: 'ss-bio-10-1',
    title: 'Cell Division Simulation',
    subject: 'Biology',
    grade: 'Grade 10',
    pathway: 'Pure Sciences',
    topicArea: 'Cell Biology',
    competency: 'Scientific Inquiry',
    durationMinutes: 50,
    description: 'Interactive mitosis and meiosis simulation',
  },
  {
    key: 'ss-bio-10-2',
    title: 'Enzyme Activity Lab',
    subject: 'Biology',
    grade: 'Grade 10',
    pathway: 'Pure Sciences',
    topicArea: 'Biochemistry',
    competency: 'Experimentation',
    durationMinutes: 50,
    description: 'Virtual enzyme reactions with pH and temperature variables',
  },
  {
    key: 'ss-bio-10-3',
    title: 'DNA Extraction Virtual Lab',
    subject: 'Biology',
    grade: 'Grade 10',
    pathway: 'Pure Sciences',
    topicArea: 'Genetics',
    competency: 'Scientific Inquiry',
    durationMinutes: 50,
    description: 'Step-by-step DNA extraction from virtual samples',
  },
  {
    key: 'ss-bio-10-4',
    title: 'Photosynthesis Simulator',
    subject: 'Biology',
    grade: 'Grade 10',
    pathway: 'Pure Sciences',
    topicArea: 'Plant Physiology',
    competency: 'Data Analysis',
    durationMinutes: 50,
    description: 'Interactive photosynthesis with light and CO2 variables',
  },
  {
    key: 'ss-bio-10-5',
    title: 'Respiratory System Simulator',
    subject: 'Biology',
    grade: 'Grade 10',
    pathway: 'Pure Sciences',
    topicArea: 'Human Physiology',
    competency: 'Systems Thinking',
    durationMinutes: 55,
    description: 'Interactive lung capacity and gas exchange simulation',
  },
  {
    key: 'ss-bio-10-6',
    title: 'Ecosystem Dynamics Lab',
    subject: 'Biology',
    grade: 'Grade 10',
    pathway: 'Pure Sciences',
    topicArea: 'Ecology',
    competency: 'Systems Thinking',
    durationMinutes: 55,
    description: 'Complex ecosystem simulator with multiple variables',
  },
  {
    key: 'ss-bio-10-7',
    title: 'PCR Simulation',
    subject: 'Biology',
    grade: 'Grade 10',
    pathway: 'Pure Sciences',
    topicArea: 'Biotechnology',
    competency: 'Scientific Inquiry',
    durationMinutes: 60,
    description: 'Virtual Polymerase Chain Reaction process',
  },
  {
    key: 'ss-bio-10-8',
    title: 'Gel Electrophoresis Lab',
    subject: 'Biology',
    grade: 'Grade 10',
    pathway: 'Pure Sciences',
    topicArea: 'Biotechnology',
    competency: 'Data Analysis',
    durationMinutes: 55,
    description: 'Virtual DNA fingerprinting and analysis',
  },

  // ===================== SENIOR SCHOOL — CHEMISTRY =====================
  {
    key: 'ss-chem-10-1',
    title: 'Titration Lab',
    subject: 'Chemistry',
    grade: 'Grade 10',
    pathway: 'Pure Sciences',
    topicArea: 'Physical Chemistry',
    competency: 'Experimentation',
    durationMinutes: 50,
    description: 'Virtual acid-base titration with indicators',
  },
  {
    key: 'ss-chem-10-2',
    title: 'Organic Chemistry Models',
    subject: 'Chemistry',
    grade: 'Grade 10',
    pathway: 'Pure Sciences',
    topicArea: 'Organic Chemistry',
    competency: 'Spatial Reasoning',
    durationMinutes: 45,
    description: '3D molecular structure builder',
  },
  {
    key: 'ss-chem-10-3',
    title: 'Electrochemical Cells',
    subject: 'Chemistry',
    grade: 'Grade 10',
    pathway: 'Pure Sciences',
    topicArea: 'Inorganic Chemistry',
    competency: 'Scientific Inquiry',
    durationMinutes: 50,
    description: 'Virtual galvanic and electrolytic cells',
  },
  {
    key: 'ss-chem-10-4',
    title: 'Reaction Rate Lab',
    subject: 'Chemistry',
    grade: 'Grade 10',
    pathway: 'Pure Sciences',
    topicArea: 'Physical Chemistry',
    competency: 'Data Analysis',
    durationMinutes: 50,
    description: 'Simulate factors affecting reaction rates',
  },
  {
    key: 'ss-chem-10-5',
    title: 'Spectroscopy Lab',
    subject: 'Chemistry',
    grade: 'Grade 10',
    pathway: 'Pure Sciences',
    topicArea: 'Analytical Chemistry',
    competency: 'Data Analysis',
    durationMinutes: 60,
    description: 'Virtual spectroscopy with different elements',
  },
  {
    key: 'ss-chem-10-6',
    title: 'Polymer Synthesis Lab',
    subject: 'Chemistry',
    grade: 'Grade 10',
    pathway: 'Pure Sciences',
    topicArea: 'Organic Chemistry',
    competency: 'Experimentation',
    durationMinutes: 55,
    description: 'Virtual polymer creation with different monomers',
  },
  {
    key: 'ss-chem-10-7',
    title: 'Chromatography Lab',
    subject: 'Chemistry',
    grade: 'Grade 10',
    pathway: 'Pure Sciences',
    topicArea: 'Analytical Chemistry',
    competency: 'Scientific Inquiry',
    durationMinutes: 50,
    description: 'Virtual paper and column chromatography',
  },
  {
    key: 'ss-chem-10-8',
    title: 'Thermochemistry Lab',
    subject: 'Chemistry',
    grade: 'Grade 10',
    pathway: 'Pure Sciences',
    topicArea: 'Physical Chemistry',
    competency: 'Data Analysis',
    durationMinutes: 50,
    description: 'Simulate calorimetry and enthalpy changes',
  },

  // ===================== SENIOR SCHOOL — PHYSICS =====================
  {
    key: 'ss-phy-10-1',
    title: 'Projectile Motion Lab',
    subject: 'Physics',
    grade: 'Grade 10',
    pathway: 'Pure Sciences',
    topicArea: 'Mechanics',
    competency: 'Scientific Inquiry',
    durationMinutes: 50,
    description: 'Interactive projectile motion with variables',
  },
  {
    key: 'ss-phy-10-2',
    title: 'Pendulum Lab',
    subject: 'Physics',
    grade: 'Grade 10',
    pathway: 'Pure Sciences',
    topicArea: 'Mechanics',
    competency: 'Data Analysis',
    durationMinutes: 45,
    description: 'Virtual pendulum with adjustable length and angle',
  },
  {
    key: 'ss-phy-10-3',
    title: 'Optics Simulator',
    subject: 'Physics',
    grade: 'Grade 10',
    pathway: 'Pure Sciences',
    topicArea: 'Waves & Optics',
    competency: 'Observation',
    durationMinutes: 50,
    description: 'Light refraction and reflection simulation',
  },
  {
    key: 'ss-phy-10-4',
    title: 'Wave Interference Lab',
    subject: 'Physics',
    grade: 'Grade 10',
    pathway: 'Pure Sciences',
    topicArea: 'Waves & Optics',
    competency: 'Scientific Inquiry',
    durationMinutes: 50,
    description: 'Advanced wave interference and diffraction',
  },
  {
    key: 'ss-phy-10-5',
    title: 'Circuit Analysis Lab',
    subject: 'Physics',
    grade: 'Grade 10',
    pathway: 'Pure Sciences',
    topicArea: 'Electricity',
    competency: 'Problem Solving',
    durationMinutes: 50,
    description: 'Complex circuit analysis with resistors, capacitors, and inductors',
  },
  {
    key: 'ss-phy-10-6',
    title: 'Electromagnetic Induction Lab',
    subject: 'Physics',
    grade: 'Grade 10',
    pathway: 'Pure Sciences',
    topicArea: 'Electricity & Magnetism',
    competency: 'Scientific Inquiry',
    durationMinutes: 55,
    description: 'Virtual generator and transformer simulation',
  },
  {
    key: 'ss-phy-10-7',
    title: 'Nuclear Decay Simulator',
    subject: 'Physics',
    grade: 'Grade 10',
    pathway: 'Pure Sciences',
    topicArea: 'Modern Physics',
    competency: 'Data Analysis',
    durationMinutes: 50,
    description: 'Simulate radioactive decay and half-life',
  },
  {
    key: 'ss-phy-10-8',
    title: 'Photoelectric Effect Lab',
    subject: 'Physics',
    grade: 'Grade 10',
    pathway: 'Pure Sciences',
    topicArea: 'Modern Physics',
    competency: 'Scientific Inquiry',
    durationMinutes: 50,
    description: 'Virtual photoelectric effect with different metals',
  },

  // ============= SENIOR SCHOOL — APPLIED SCIENCES: AGRICULTURE =============
  {
    key: 'ss-agr-10-1',
    title: 'Soil Analysis Lab',
    subject: 'Agriculture',
    grade: 'Grade 10',
    pathway: 'Applied Sciences - Agriculture',
    topicArea: 'Crop Science',
    competency: 'Scientific Inquiry',
    durationMinutes: 50,
    description: 'Virtual soil testing for pH, nutrients, and composition',
  },
  {
    key: 'ss-agr-10-2',
    title: 'Hydroponics Simulator',
    subject: 'Agriculture',
    grade: 'Grade 10',
    pathway: 'Applied Sciences - Agriculture',
    topicArea: 'Crop Science',
    competency: 'Innovation',
    durationMinutes: 55,
    description: 'Interactive hydroponic system with different solutions',
  },
  {
    key: 'ss-agr-10-3',
    title: 'Greenhouse Management',
    subject: 'Agriculture',
    grade: 'Grade 10',
    pathway: 'Applied Sciences - Agriculture',
    topicArea: 'Crop Science',
    competency: 'Systems Thinking',
    durationMinutes: 55,
    description: 'Virtual greenhouse with climate control',
  },
  {
    key: 'ss-agr-10-4',
    title: 'Livestock Management Sim',
    subject: 'Agriculture',
    grade: 'Grade 10',
    pathway: 'Applied Sciences - Agriculture',
    topicArea: 'Animal Science',
    competency: 'Data Analysis',
    durationMinutes: 50,
    description: 'Track livestock health, feeding, and breeding',
  },

  // ========= SENIOR SCHOOL — APPLIED SCIENCES: COMPUTER STUDIES =========
  {
    key: 'ss-cs-10-1',
    title: 'Network Topology Builder',
    subject: 'Computer Studies',
    grade: 'Grade 10',
    pathway: 'Applied Sciences - Computer Studies',
    topicArea: 'Networking',
    competency: 'Systems Thinking',
    durationMinutes: 50,
    description: 'Build and test network topologies',
  },
  {
    key: 'ss-cs-10-2',
    title: 'Cybersecurity Simulator',
    subject: 'Computer Studies',
    grade: 'Grade 10',
    pathway: 'Applied Sciences - Computer Studies',
    topicArea: 'Security',
    competency: 'Critical Thinking',
    durationMinutes: 55,
    description: 'Virtual cyber attack and defense simulation',
  },
  {
    key: 'ss-cs-10-3',
    title: 'Database Design Lab',
    subject: 'Computer Studies',
    grade: 'Grade 10',
    pathway: 'Applied Sciences - Computer Studies',
    topicArea: 'Database',
    competency: 'Design Thinking',
    durationMinutes: 50,
    description: 'Interactive database schema design',
  },
  {
    key: 'ss-cs-10-4',
    title: 'Algorithm Visualizer',
    subject: 'Computer Studies',
    grade: 'Grade 10',
    pathway: 'Applied Sciences - Computer Studies',
    topicArea: 'Programming',
    competency: 'Problem Solving',
    durationMinutes: 50,
    description: 'Visualize sorting and searching algorithms',
  },

  // ================= SENIOR SCHOOL — TECHNICAL STUDIES =================
  {
    key: 'ss-tech-10-1',
    title: 'Aviation Simulator',
    subject: 'Technical Studies',
    grade: 'Grade 10',
    pathway: 'Technical Studies',
    topicArea: 'Aviation',
    competency: 'Observation',
    durationMinutes: 55,
    description: 'Flight principles and navigation simulation',
  },
  {
    key: 'ss-tech-10-2',
    title: 'Building Design Studio',
    subject: 'Technical Studies',
    grade: 'Grade 10',
    pathway: 'Technical Studies',
    topicArea: 'Building & Construction',
    competency: 'Design Thinking',
    durationMinutes: 60,
    description: '3D architectural design and structural analysis',
  },
  {
    key: 'ss-tech-10-3',
    title: 'Electrical Workshop',
    subject: 'Technical Studies',
    grade: 'Grade 10',
    pathway: 'Technical Studies',
    topicArea: 'Electricity',
    competency: 'Problem Solving',
    durationMinutes: 55,
    description: 'Virtual electrical installation and fault finding',
  },
  {
    key: 'ss-tech-10-4',
    title: 'Automotive Diagnostics',
    subject: 'Technical Studies',
    grade: 'Grade 10',
    pathway: 'Technical Studies',
    topicArea: 'Power Mechanics',
    competency: 'Scientific Inquiry',
    durationMinutes: 55,
    description: 'Virtual engine diagnostics and repair simulation',
  },

  // ===================== PILOT LAB — fully built out =====================
  // Video + narration + quiz all wired up, per the "1 full pilot lab"
  // scoping decision. Not part of the original curriculum table — added as
  // a working example of the video-watch-then-quiz flow. Set to Grade 7 so
  // it's immediately testable against seed.ts's demo student (ADM001, Grade
  // 7) without extra setup; adjust via PATCH /labs/:id if you'd rather slot
  // it elsewhere.
  {
    key: 'demo-volcano-1',
    title: 'Volcano Eruption: How and Why',
    subject: 'Integrated Science',
    grade: 'Grade 7',
    topicArea: 'Earth Science',
    competency: 'Scientific Inquiry',
    durationMinutes: 6,
    description: 'Watch a real volcanic eruption and learn what causes magma to force its way to the surface, then answer questions to check your understanding.',
    // NOTE: verify this is the intended video before publishing to students —
    // extracted from the search link provided during development.
    resourceUrl: 'https://www.youtube.com/embed/EH4l4pvmwXs',
    guidanceSteps: [
      "Hi there! I'm your STEM Labs guide. Today we're exploring one of the most powerful forces on our planet: volcanic eruptions.",
      'Watch the video carefully. Pay attention to how magma moves underground, what causes pressure to build up, and what actually comes out of a volcano when it erupts.',
      "Once you're done watching, I'll ask you a few questions to see what you've learned. Take your time and think it through!",
    ],
    questions: [
      {
        questionText: 'What is molten rock called before it erupts out of a volcano?',
        questionType: QuestionType.MULTIPLE_CHOICE,
        options: ['Lava', 'Magma', 'Ash', 'Pumice'],
        correctAnswer: 'Magma',
        points: 20,
        order: 0,
      },
      {
        questionText: 'Lava and magma are exactly the same thing, just with different names depending on the country.',
        questionType: QuestionType.TRUE_FALSE,
        options: ['True', 'False'],
        correctAnswer: 'False',
        points: 20,
        order: 1,
      },
      {
        questionText: 'What mainly causes a volcano to erupt?',
        questionType: QuestionType.MULTIPLE_CHOICE,
        options: ['Pressure from trapped gases in magma', 'Ocean tides', 'Wind pressure', 'Earthquakes happening far away'],
        correctAnswer: 'Pressure from trapped gases in magma',
        points: 20,
        order: 2,
      },
      {
        questionText: 'Which of these is NOT typically released during a volcanic eruption?',
        questionType: QuestionType.MULTIPLE_CHOICE,
        options: ['Lava', 'Volcanic ash', 'Gases like sulfur dioxide', 'Liquid nitrogen'],
        correctAnswer: 'Liquid nitrogen',
        points: 20,
        order: 3,
      },
      {
        questionText: 'Scientists can help predict some volcanic eruptions by monitoring gas emissions, ground swelling, and earthquake activity near a volcano.',
        questionType: QuestionType.TRUE_FALSE,
        options: ['True', 'False'],
        correctAnswer: 'True',
        points: 20,
        order: 4,
      },
    ],
  },
];
