import { AiFeature } from "@prisma/client";

export const AI_EXTRACTION_PROMPT_VERSION = "topics-v1";
export const AI_ASSIGNMENT_PROMPT_VERSION = "topic-assignment-v1";
export const AI_SOURCE_MAX_BYTES = 15 * 1024 * 1024;
export const AI_SOURCE_TEXT_MAX_CHARACTERS = 100_000;
export const AI_TOPIC_CONTEXT_MAX_CHARACTERS = 60_000;

export const AI_FEATURE_ENV_FLAGS: Record<AiFeature, string> = {
  [AiFeature.ASSIGNMENT_DRAFT]: "AI_ASSIGNMENT_DRAFTS_ENABLED",
  [AiFeature.QUESTION_SET]: "AI_QUESTION_SETS_ENABLED",
  [AiFeature.FEEDBACK_DRAFT]: "AI_FEEDBACK_DRAFTS_ENABLED",
  [AiFeature.GRADING_SUGGESTION]: "AI_GRADING_SUGGESTIONS_ENABLED",
  [AiFeature.LEARNING_RECOMMENDATION]: "AI_LEARNING_RECOMMENDATIONS_ENABLED",
};
