import { api } from './axios';
import type { School } from '../types';

// Matches backend/src/schools/schools.controller.ts + dto/create-school.dto.ts
// EXACTLY. Two things worth flagging (see ROADMAP.md):
//  - POST / is PLATFORM_ADMIN-only — no self-service "school admin signs up"
//    flow exists.
//  - `code` is REQUIRED and NOT auto-generated by the backend
//    (SchoolsService.create just persists whatever `code` is passed —
//    see schools.service.ts). The caller must supply a unique code matching
//    /^[A-Z0-9]+$/, 3-20 chars. The frontend suggests one for convenience
//    (see PlatformAdminDashboard.tsx) but it's a client-side suggestion, not
//    a real server-generated value.
export const schoolsApi = {
  create: (dto: {
    name: string;
    code: string;
    type?: 'DAY' | 'BOARDING';
    logoUrl?: string;
    address?: string;
    phone?: string;
    contactEmail?: string;
  }) => api.post<School>('/schools', dto).then((r) => r.data),

  findAll: () => api.get<School[]>('/schools').then((r) => r.data),

  findOne: (id: number) => api.get<School>(`/schools/${id}`).then((r) => r.data),

  // UpdateSchoolDto omits `code` (immutable after creation) — never send it.
  update: (
    id: number,
    dto: Partial<Pick<School, 'name' | 'logoUrl' | 'address' | 'phone' | 'contactEmail' | 'type'>>,
  ) => api.patch<School>(`/schools/${id}`, dto).then((r) => r.data),
};
